version: '3.8'

services:
  app:
    image: mcamacho10/qualitative-interviews:latest
    depends_on:
      db:
        condition: service_healthy
    container_name: app
    ports:
      - "8000:80"
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chats
      - APP_ENV=DEV
      - OPENAI_API_KEY=REPLACE_ME_WITH_YOUR_OPENAI_API_KEY
    volumes:
      - ./app:/app
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chats
    hostname: localhost
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - .dbdata:/var/lib/postgresql/data
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

volumes:
  .dbdata:
