AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: serverless-interviews

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60       # 60 seconds
    MemorySize: 128   # 128MB function memory
    Runtime: python3.13
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. 
    # Learn more here:
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
      SystemLogLevel: WARN          # Change as you see fit
      ApplicationLogLevel: ERROR    # Change as you see fit
    Architectures:
      - arm64 
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  InterviewFunction:
    # More info about Function Resource: 
    # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function   
    Properties:
      CodeUri: app/
      Handler: lambda.handler
      Events:
        Interview:
          # More info about API Event Source: 
          # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Type: Api 
          Properties:
            Path: /next
            Method: post
      Environment:
        Variables:
          DATABASE: DYNAMODB
          DATABASE_URL: !Ref DBTable
          PORT: 8000  # required for the Lambda Web Adapter
          OPENAI_API_KEY: YOUR_OPENAI_API_KEY # MAKE SURE TO REPLACE THIS WITH YOUR ACTUAL KEY!
    Connectors:
      DBTableConnector:
        Properties:
          Destination: 
            Id: DBTable
          Permissions: 
            - Read
            - Write 
  DBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InterviewApi:
    Description: API Gateway endpoint URL for function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/next/"
  DynamoDBTable:
    Description: DynamoDB Table
    Value: !Ref DBTable
